name: Daily Commit

on:
  schedule:
    - cron: "0 3 * * *"  # Runs daily at 3 AM UTC (Adjust as needed)

  workflow_dispatch: # Allows manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Make a dummy change (23ds2000069@ds.study.iitm.ac.in)
        run: |
          echo "Last run: $(date)" > last-run.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "23ds2000069@ds.study.iitm.ac.in"
          git add last-run.txt
          git commit -m "Automated commit - $(date)"
          git push
